services:
  app:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./:/app
    command:
      [
        '/bin/sh',
        '-c',
        'rm -rf apps/web/dist apps/api/dist packages/database/dist && bun install && bun run build && bun run start',
      ]
    ports:
      - '127.0.0.1:${APP_PORT:-3000}:${APP_PORT:-3000}'
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
      APP_PORT: ${APP_PORT:-3000}
      DB_HOST: prod_db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-atlas_db}
      DB_USER: ${DB_USER:-atlas_user}
      DB_PASSWORD: ${DB_PASSWORD:-p@$$w0rd}
      ARGON2ID_MEMORY: ${ARGON2ID_MEMORY:-65536}
      ARGON2ID_TIME: ${ARGON2ID_TIME:-3}
      PWD_PEPPER: ${PWD_PEPPER:-zwjDTxT5YxdWrcBnemVd1g==}
    depends_on:
      prod_db:
        condition: service_healthy

  prod_db:
    image: mariadb:12
    env_file:
      - ../.env
    environment:
      MARIADB_DATABASE: ${DB_NAME:-atlas_db}
      MARIADB_USER: ${DB_USER:-atlas_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-p@$$w0rd}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@$$w0rd}
    volumes:
      - db-prod-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mariadb-admin ping -h localhost -u$$MARIADB_USER -p$$MARIADB_PASSWORD || exit 1',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-prod-data:
