services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME:-atlas-dev}
      MYSQL_USER: ${DB_USER:-atlasdev}
      MYSQL_PASSWORD: ${DB_PASSWORD:-p@$$w0rd}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@$$w0rd}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '${DB_PORT:-3306}:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h localhost -u$DB_USER -p$DB_PASSWORD || exit 1']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-data:
