services:
  test_app:
    build:
      context: .
      dockerfile: dockerfile.test
    volumes:
      - .:/app
    ports:
      - '${APP_PORT:-3005}:3005'
    depends_on:
      test_db:
        condition: service_healthy

  test_db:
    image: mariadb:12
    environment:
      MARIADB_DATABASE: ${DB_NAME:-atlas-dev-test}
      MARIADB_USER: ${DB_USER:-atlastest}
      MARIADB_PASSWORD: ${DB_PASSWORD:-p@$$w0rd}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@$$w0rd}
    volumes:
      - db-test-data:/var/lib/mysql

    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h localhost -u$DB_USER -p$DB_PASSWORD || exit 1']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-test-data:
