services:
  dev_app:
    build:
      context: ../../
      dockerfile: packages/database/Dockerfile
    working_dir: /app/packages/database
    volumes:
      - ../../:/app
    ports:
      - '${APP_PORT:-5000}'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: ${DB_HOST:-dev_db}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-atlas_db}
      DB_USER: ${DB_USER:-atlas_user}
      DB_PASSWORD: ${DB_PASSWORD:-p@$$w0rd}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@ssw0rd}
      ARGON2ID_MEMORY: ${ARGON2ID_MEMORY:-65536}
      ARGON2ID_TIME: ${ARGON2ID_TIME:-3}
      PWD_PEPPER: ${PWD_PEPPER:-zwjDTxT5YxdWrcBnemVd1g==}
    depends_on:
      dev_db:
        condition: service_healthy

  dev_db:
    image: mariadb:12
    environment:
      MARIADB_DATABASE: ${DB_NAME:-atlas_db}
      MARIADB_USER: ${DB_USER:-atlas_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-p@$$w0rd}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@$$w0rd}
    volumes:
      - db-dev-data:/var/lib/mysql
    ports:
      - '${DB_PORT:-3306}:3306'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mariadb-admin ping -h localhost -u$$MARIADB_USER -p$$MARIADB_PASSWORD || exit 1',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-dev-data:
