services:
  test_app:
    build:
      context: ../../
      dockerfile: packages/database/Dockerfile
    working_dir: /app/packages/database
    env_file:
      - ../../.env.test
    volumes:
      - ../../:/app
    ports:
      - '${APP_PORT:-5005}'
    environment:
      NODE_ENV: ${NODE_ENV:-test}
      APP_PORT: ${APP_PORT:-5005}
      DB_HOST: ${DB_HOST:-test_db}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-atlas_db_test}
      DB_USER: ${DB_USER:-test_user}
      DB_PASSWORD: ${DB_PASSWORD:-test_password}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@ssw0rd}
      ARGON2ID_MEMORY: ${ARGON2ID_MEMORY:-65536}
      ARGON2ID_TIME: ${ARGON2ID_TIME:-3}
      PWD_PEPPER: ${PWD_PEPPER:-zwjDTxT5YxdWrcBnemVd1g==}
    depends_on:
      test_db:
        condition: service_healthy

  test_db:
    image: mariadb:12
    environment:
      MARIADB_DATABASE: ${DB_NAME:-atlas_db_test}
      MARIADB_USER: ${DB_USER:-test_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-test_password}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootp@$$w0rd}
    volumes:
      - db-test-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mariadb-admin ping -h localhost -u$$MARIADB_USER -p$$MARIADB_PASSWORD || exit 1',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-test-data:
