name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: oven/bun:1.3.6
    env:
      NODE_ENV: test
      DB_HOST: test_db
      DB_PORT: 3306
      DB_NAME: atlas_db_test
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_ROOT_PASSWORD: rootp@ssword
      APP_PORT: 3000

    services:
      test_db:
        image: mariadb:12
        env:
          MARIADB_DATABASE: atlas_db_test
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
          MARIADB_ROOT_PASSWORD: rootp@ssword
        options: >-
          --health-cmd="mariadb-admin ping -h localhost -utest_user -ptest_password"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun run tests
